"""Migrate

Revision ID: 0d04a1d73a9c
Revises: 197b914a0b1b
Create Date: 2019-09-27 16:09:41.344748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d04a1d73a9c'
down_revision = '197b914a0b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('blogerss', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blogerss'], ['blogers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
