"""Migration

Revision ID: 197b914a0b1b
Revises: 2c295b34a230
Create Date: 2019-09-26 21:52:15.746584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197b914a0b1b'
down_revision = '2c295b34a230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('texto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogers')
    # ### end Alembic commands ###
