"""Migrate

Revision ID: 5e21396f432e
Revises: 0d04a1d73a9c
Create Date: 2019-09-27 17:55:36.995836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e21396f432e'
down_revision = '0d04a1d73a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic_path', sa.String(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogers', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogers', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogers', type_='foreignkey')
    op.drop_column('blogers', 'user')
    op.drop_table('profiles')
    # ### end Alembic commands ###
