"""Migrate

Revision ID: cccf5a441b3d
Revises: 5e21396f432e
Create Date: 2019-09-30 19:46:37.756366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccf5a441b3d'
down_revision = '5e21396f432e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user')
    op.drop_table('subscribe')
    # ### end Alembic commands ###
